apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1","kind":"Task","metadata":{"annotations":{},"name":"git-commit-push","namespace":"hello-http-ci"},"spec":{"params":[{"default":"repo","name":"repoDir","type":"string"},{"default":"tekton-ci","name":"gitUserName","type":"string"},{"default":"tekton-ci@example.com","name":"gitUserEmail","type":"string"},{"default":"CI: update manifests","name":"commitMessage","type":"string"},{"default":"apps/hello-http/manifests/deploy.yaml","name":"fileToEdit","type":"string"},{"default":"s#replicas: 1#replicas: 1#","name":"sedExpr","type":"string"}],"steps":[{"image":"docker.io/alpine/git:latest","name":"edit-commit-push","script":"#!/bin/sh\nset -eux\n\ngit config user.name \"$(params.gitUserName)\"\ngit config user.email \"$(params.gitUserEmail)\"\n\n# Edit\nsed -i \"$(params.sedExpr)\" \"$(params.fileToEdit)\"\n\n# Show diff (debug)\ngit diff || true\n\n# Commit if changes exist\nif [ -n \"$(git status --porcelain)\" ]; then\n  git add \"$(params.fileToEdit)\"\n  git commit -m \"$(params.commitMessage)\"\n  git push origin HEAD\nelse\n  echo \"No changes to commit.\"\nfi\n","workingDir":"$(workspaces.output.path)/$(params.repoDir)"}],"workspaces":[{"name":"output"}]}}
  creationTimestamp: "2026-02-20T02:01:15Z"
  generation: 2
  name: git-commit-push
  namespace: hello-http-ci
  resourceVersion: "293583"
  uid: 5afa79d4-c51b-4647-a8d9-05c9246dbbff
spec:
  params:
  - default: repo
    name: repoDir
    type: string
  - default: tekton-ci
    name: gitUserName
    type: string
  - default: tekton-ci@example.com
    name: gitUserEmail
    type: string
  - default: 'CI: update manifests'
    name: commitMessage
    type: string
  - default: apps/hello-http/manifests/deploy.yaml
    name: fileToEdit
    type: string
  - default: 's#replicas: 1#replicas: 1#'
    name: sedExpr
    type: string
  steps:
  - computeResources: {}
    image: docker.io/alpine/git:latest
    name: edit-commit-push
    script: |
      #!/bin/sh
      set -eux

      echo "PWD=$(pwd)"
      echo "Workspace output path: $(workspaces.output.path)"
      ls -la "$(workspaces.output.path)" || true

      # buscar el .git (primer match)
      REPO_ROOT=$(find "$(workspaces.output.path)" -maxdepth 4 -type d -name .git | head -n 1 | sed "s#/.git##")

      echo "Detected repo root: ${REPO_ROOT}"
      [ -n "${REPO_ROOT}" ]
      cd "${REPO_ROOT}"

      git status

      git config user.name "$(params.gitUserName)"
      git config user.email "$(params.gitUserEmail)"

      # Edit
      sed -i "$(params.sedExpr)" "$(params.fileToEdit)"

      git diff || true

      if [ -n "$(git status --porcelain)" ]; then
        git add "$(params.fileToEdit)"
        git commit -m "$(params.commitMessage)"
        git push origin HEAD
      else
        echo "No changes to commit."
      fi
    workingDir: $(workspaces.output.path)/$(params.repoDir)
  workspaces:
  - name: output
